packages:
  - 'packages/*'
  - doc
  - docs

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  lefthook: true
  msw: true
  vue-demi: true

peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - postcss
    - search-insights

packageExtensions:
  sass-embedded:
    peerDependencies:
      source-map-js: '*'
    peerDependenciesMeta:
      source-map-js:
        optional: true

catalog:
  vue: ^3.5.38
  tsdown: ^0.22.2
  vite: ^8.0.16
  vitest: ^4.1.9

minimumReleaseAgeExclude:
  - '@rspress/core@2.0.14'
  - '@rspress/shared@2.0.14'
  - '@vitest/expect@4.1.9'
  - '@vitest/mocker@4.1.9'
  - '@vitest/pretty-format@4.1.9'
  - '@vitest/runner@4.1.9'
  - '@vitest/snapshot@4.1.9'
  - '@vitest/spy@4.1.9'
  - '@vitest/utils@4.1.9'
  - vitest@4.1.9
