allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  lefthook: true
  less: true
  protobufjs: true
patchedDependencies:
  '@tarojs/plugin-mini-ci': patches/@tarojs__plugin-mini-ci.patch
