
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout  65;

    server {
        listen 9981;
        location / {
            proxy_pass http://localhost:9980/;
        }
    }
}
