services:
  postgres:
    image: postgres:18-alpine
    container_name: vp-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ml
    ports:
      - '5432:5432'
    volumes:
      - postgres18-data:/var/lib/postgresql
  redis:
    image: redis:8-alpine
    container_name: vp-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ml
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    container_name: vp-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
  minio-init:
    image: minio/mc:latest
    container_name: vp-minio-init
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123456
      MINIO_BUCKET: uploads
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 $$MINIO_ROOT_USER
      $$MINIO_ROOT_PASSWORD;
      do sleep 1; done;
      mc mb --ignore-existing local/$$MINIO_BUCKET;
      mc anonymous set none local/$$MINIO_BUCKET;
      "
    restart: 'no'

volumes:
  postgres18-data:
  redis-data:
  minio-data:
