packages:
  - apps/*
  - packages/*

catalogMode: prefer

catalog:
  '@types/node': ^26.0.1
  typescript: ^6
  tsdown: latest
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
  '@commitlint/cli': ^21.1.0
  '@commitlint/config-conventional': ^21.1.0
  cross-env: ^10.1.0
  '@nestjs/platform-fastify': ^11.1.27
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
minimumReleaseAgeExclude:
  - axios@1.18.1
