packages:
  - apps/*
  - packages/*
  - packages/i18n/*

catalogMode: prefer

catalog:
  '@types/node': ^26.0.1
  typescript: ^7
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
  '@commitlint/cli': ^21.1.0
  '@commitlint/config-conventional': ^21.1.0
  cross-env: ^10.1.0
overrides:
  vite: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'
minimumReleaseAgeExclude:
  - axios@1.18.1
allowBuilds:
  '@parcel/watcher': true
  lefthook: true
